name: Rust CI with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: hecrj/setup-rust-action@v1.4.1
        with:
          rust-version: stable

      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build Docker image (arm64)
        run: |
          cd apps/rw-admin
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/arm64 . --file Dockerfile --tag ${{ vars.hubAddr }}/${{ vars.USER_NAME }}/${{ vars.IMAGE_NAME }}:${{ vars.tag }} &
        id: build_arm64

      - name: Build Docker image (amd64)
        run: |
          cd apps/rw-admin
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64 . --file Dockerfile --tag ${{ vars.hubAddr }}/${{ vars.USER_NAME }}/${{ vars.IMAGE_NAME }}:${{ vars.tag }} &
        id: build_amd64

      - name: Log in to Docker registry
        run: |
          docker login --username=${{ secrets.DOCKER_HUB_USERNAME }} --password=${{ secrets.DOCKER_HUB_PASSWORD }} registry.cn-hangzhou.aliyuncs.com

      - name: Wait for Docker builds to complete
        run: |
          while [[ "$(docker buildx inspect --bootstrap)" != *"Status: completed"* ]]; do
            sleep 10
          done

      - name: Push Docker image
        run: |
          docker push ${{ vars.hubAddr }}/${{ vars.USER_NAME }}/${{ vars.IMAGE_NAME }}:${{ vars.tag }}
